import React from "react";
import {
  FileText,
  Printer,
  Download,
  ShieldCheck,
  AlertTriangle,
  MapPin,
  Clock,
  Compass,
  Ship,
  Waves,
  Calendar,
  Layers,
  CheckCircle2,
} from "lucide-react";

export default function ReportsPage({
  spill,
  origin,
  suspects = [],
  forecast = [],
  impact = null,
}) {
  const handlePrint = () => {
    window.print();
  };

  const topSuspect = suspects[0];
  const lat = spill?.centroid?.lat || spill?.latitude || 15.462;
  const lon = spill?.centroid?.lon || spill?.longitude || 73.845;
  const originLat = origin?.estimatedOrigin?.lat || origin?.latitude || 15.201;
  const originLon = origin?.estimatedOrigin?.lon || origin?.longitude || 73.512;

  return (
    <div className="page-container report-page-container">
      {/* TOOLBAR */}
      <div className="report-action-bar no-print">
        <div>
          <span className="eyebrow">OFFICIAL DOSSIER</span>
          <h2>Incident Investigation Report</h2>
          <p className="text-muted">
            Generated by BlueGuard AI Maritime Intelligence Engine • SIH 26143
          </p>
        </div>

        <div className="report-btn-group">
          <button
            type="button"
            className="secondary-btn"
            onClick={handlePrint}
          >
            <Printer size={16} /> Print / Save as PDF
          </button>
        </div>
      </div>

      {/* PRINTABLE DOSSIER CARD */}
      <div className="report-sheet panel printable-area">
        {/* REPORT HEADER */}
        <div className="report-header">
          <div className="report-brand">
            <div className="brand-badge">BLUEGUARD AI</div>
            <div>
              <h1>MARINE OIL SPILL INVESTIGATION DOSSIER</h1>
              <p>National Coastal Intelligence & Spill Attribution Service</p>
            </div>
          </div>

          <div className="report-meta-box">
            <div>
              <span>REPORT ID:</span>
              <strong>RPT-{spill?.spillId || "SP101"}-2026</strong>
            </div>
            <div>
              <span>DATE GENERATED:</span>
              <strong>{new Date().toISOString().replace("T", " ").slice(0, 19)} UTC</strong>
            </div>
            <div>
              <span>STATUS:</span>
              <strong className="text-success">INVESTIGATION COMPLETE</strong>
            </div>
          </div>
        </div>

        <hr className="report-divider" />

        {/* 1. DETECTION & SATELLITE METADATA */}
        <div className="report-section">
          <div className="section-title">
            <span className="step-num">1</span>
            <h3>Satellite Image Detection & Telemetry</h3>
          </div>

          <div className="report-table-wrap">
            <table className="report-table">
              <tbody>
                <tr>
                  <td className="w-25">Incident ID</td>
                  <td className="w-25"><strong>{spill?.spillId || "SP101"}</strong></td>
                  <td className="w-25">Satellite Platform</td>
                  <td className="w-25"><strong>{spill?.sensor || "Sentinel-1 SAR IW"}</strong></td>
                </tr>
                <tr>
                  <td>Acquisition Time</td>
                  <td>{spill?.detectedAt || "2026-08-29 10:00:00 UTC"}</td>
                  <td>Observation Band</td>
                  <td>C-Band Synthetic Aperture Radar (VV Polarization)</td>
                </tr>
                <tr>
                  <td>Detection Centroid</td>
                  <td><strong>{lat.toFixed(4)}° N, {lon.toFixed(4)}° E</strong></td>
                  <td>Geographic Sector</td>
                  <td>{spill?.region || "Arabian Sea (Goa Coast)"}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        {/* 2. SPILL CHARACTERIZATION */}
        <div className="report-section">
          <div className="section-title">
            <span className="step-num">2</span>
            <h3>Spill Characterization & AI Assessment</h3>
          </div>

          <div className="report-stats-grid">
            <div className="report-stat-card">
              <span>Slick Area</span>
              <strong>{spill?.areaSqKm || 12.5} km²</strong>
            </div>
            <div className="report-stat-card">
              <span>AI Detection Confidence</span>
              <strong className="text-accent">
                {Math.round((spill?.confidence > 1 ? spill?.confidence : (spill?.confidence || 0.91) * 100))}%
              </strong>
            </div>
            <div className="report-stat-card">
              <span>Assessed Severity</span>
              <strong className="text-danger">{spill?.severity || "HIGH"}</strong>
            </div>
            <div className="report-stat-card">
              <span>Neural Model</span>
              <strong>{spill?.modelVersion || "UNet_ResNet34_v1"}</strong>
            </div>
          </div>
        </div>

        {/* 3. ORIGIN / BACKTRACKING */}
        <div className="report-section">
          <div className="section-title">
            <span className="step-num">3</span>
            <h3>GIS Backtracking Simulation (Estimated Origin)</h3>
          </div>

          <div className="report-table-wrap">
            <table className="report-table">
              <tbody>
                <tr>
                  <td className="w-25">Estimated Release Location</td>
                  <td className="w-25"><strong>{originLat.toFixed(4)}° N, {originLon.toFixed(4)}° E</strong></td>
                  <td className="w-25">Uncertainty Radius</td>
                  <td className="w-25">±{origin?.uncertaintyKm || 12.0} km</td>
                </tr>
                <tr>
                  <td>Estimated Release Time</td>
                  <td><strong>{origin?.estimatedTime || "2026-08-28 23:40:00 UTC"}</strong></td>
                  <td>Backtrack Window</td>
                  <td>10 Hours 20 Minutes prior to satellite pass</td>
                </tr>
                <tr>
                  <td>Drift Model Engine</td>
                  <td>Hydrodynamic Advection Drift (3% Wind Vector + Surface Currents)</td>
                  <td>Origin Confidence</td>
                  <td><strong>{Math.round((origin?.confidence || 0.81) * 100)}%</strong></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        {/* 4. CANDIDATE VESSELS & AIS TELEMETRY */}
        <div className="report-section">
          <div className="section-title">
            <span className="step-num">4</span>
            <h3>AIS Candidate Vessels Correlated</h3>
          </div>

          <div className="report-table-wrap">
            <table className="report-table candidate-table">
              <thead>
                <tr>
                  <th>Rank</th>
                  <th>Vessel Name</th>
                  <th>MMSI</th>
                  <th>Type</th>
                  <th>Flag</th>
                  <th>Distance to Origin</th>
                  <th>Time Delta</th>
                  <th>Attribution Score</th>
                  <th>Priority</th>
                </tr>
              </thead>
              <tbody>
                {suspects.map((v, idx) => (
                  <tr key={v.vesselId || v.mmsi || idx}>
                    <td>#{idx + 1}</td>
                    <td><strong>{v.name}</strong></td>
                    <td>{v.mmsi}</td>
                    <td>{v.vesselType || v.type}</td>
                    <td>{v.flagCountry || "IN"}</td>
                    <td>{v.evidence?.distanceKm ?? "-"} km</td>
                    <td>{v.evidence?.timeDifferenceMin ?? "-"} min</td>
                    <td><strong>{v.score}%</strong></td>
                    <td>
                      <span className="badge-critical">
                        {v.evidence?.investigationPriority || "Medium"}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* 5. ATTRIBUTION EVIDENCE BREAKDOWN */}
        {topSuspect && (
          <div className="report-section">
            <div className="section-title">
              <span className="step-num">5</span>
              <h3>Primary Suspect Attribution Evidence ({topSuspect.name})</h3>
            </div>

            <div className="evidence-report-box">
              <p>
                <strong>Investigative Rationale:</strong> {topSuspect.whySuspicious}
              </p>

              <div className="evidence-factors-summary">
                <div>
                  <span>Spatial Proximity (30%):</span>
                  <strong>{Math.round((topSuspect.evidence?.spatialProximity || 0.98) * 100)}%</strong>
                </div>
                <div>
                  <span>Temporal Proximity (25%):</span>
                  <strong>{Math.round((topSuspect.evidence?.temporalProximity || 0.95) * 100)}%</strong>
                </div>
                <div>
                  <span>Route Consistency (20%):</span>
                  <strong>{Math.round((topSuspect.evidence?.routeConsistency || 0.92) * 100)}%</strong>
                </div>
                <div>
                  <span>Heading Consistency (15%):</span>
                  <strong>{Math.round((topSuspect.evidence?.headingConsistency || 0.94) * 100)}%</strong>
                </div>
                <div>
                  <span>AIS Continuity (10%):</span>
                  <strong>{Math.round((topSuspect.evidence?.aisContinuity || 0.96) * 100)}%</strong>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* 6. FORWARD DRIFT FORECAST */}
        <div className="report-section">
          <div className="section-title">
            <span className="step-num">6</span>
            <h3>Forward Drift & Shoreline Impact Forecast</h3>
          </div>

          <div className="report-table-wrap">
            <table className="report-table">
              <thead>
                <tr>
                  <th>Horizon</th>
                  <th>Forecast Timestamp (UTC)</th>
                  <th>Predicted Coordinates</th>
                  <th>Predicted Slick Area</th>
                  <th>Uncertainty Radius</th>
                  <th>Shoreline Risk Assessment</th>
                </tr>
              </thead>
              <tbody>
                {forecast.map((f) => (
                  <tr key={f.hours}>
                    <td><strong>+{f.hours} Hours</strong></td>
                    <td>{f.time}</td>
                    <td>{f.lat.toFixed(3)}° N, {f.lon.toFixed(3)}° E</td>
                    <td>{f.areaSqKm} km²</td>
                    <td>±{f.uncertaintyKm} km</td>
                    <td>
                      {f.hours === 72 ? (
                        <span className="text-danger font-bold">
                          Coastal Landfall Warning (Goa beaches)
                        </span>
                      ) : (
                        "Open Sea Drift (East-Northeast)"
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* 7. ENVIRONMENTAL IMPACT */}
        <div className="report-section">
          <div className="section-title">
            <span className="step-num">7</span>
            <h3>Environmental & Socio-Economic Impact</h3>
          </div>

          <div className="report-table-wrap">
            <table className="report-table">
              <tbody>
                <tr>
                  <td className="w-25">Coastal Zone Risk</td>
                  <td className="w-25 text-danger font-bold">{impact?.coastalRisk || "CRITICAL"}</td>
                  <td className="w-25">Marine Ecological Risk</td>
                  <td className="w-25 text-warning font-bold">{impact?.marineRisk || "HIGH"}</td>
                </tr>
                <tr>
                  <td>Fishery Exposure</td>
                  <td className="text-warning font-bold">{impact?.fishingRisk || "MEDIUM"}</td>
                  <td>Total Vulnerable Area</td>
                  <td><strong>{impact?.affectedAreaSqKm || 42.6} km²</strong></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        {/* 8. LEGAL DISCLAIMER */}
        <div className="report-disclaimer">
          <strong>LEGAL & INVESTIGATIVE NOTICE:</strong>
          <p>
            This document is generated by BlueGuard AI as an investigation-support decision aid. Vessel attribution scores represent empirical Bayesian correlation based on recorded AIS transponder data and numerical ocean drift modeling. Attribution rankings do not constitute an automatic judicial determination of legal liability.
          </p>
        </div>
      </div>
    </div>
  );
}
